### ISSUE TITLE
I want to know how long training takes when using 4 12G NVIDIA 3090 GPUs as paper mention.

### ISSUE THREAD

**Issue by Li-ChangHao** [hustvl/Symphonies#10]
Hello, what a great job！When I use 3 NVIDIA 3090 GPUs for training, it takes more than 4 hours to train one epoch. Is this normal? So I wonder how long does training take when using 4 12G NVIDIA 3090 GPUs as paper mention.

**Comment by npurson** [comment]
Thank you for your enthusiasm for our work!

The training duration you mentioned is much longer than expected. In our training cases, it typically takes a little less than 1 day to train on SemanticKITTI, and ~1.2 d to train on SSCBench-KITTI-360. For more details, you can check the provided logs in the [README](https://github.com/hustvl/Symphonies?tab=readme-ov-file#results).

**Comment by npurson** [comment]
Perhaps you could examine the GPU utilization rates and the time costs for each module to identify whether the potential bottlenecks lie in disk I/O or any specific module.

BTW, I recall there were some compatibility issues in the latest Lightning update regarding Distributed Data Parallel (DDP). Training on a single GPU without DDP can help diagnose whether the issue is related to DDP.

**Comment by Li-ChangHao** [comment]
Thank you very much for your answer, I found that I was using a dataset that included every frame of data, which was 5 times larger than the original dataset. It does take just over 1 day to train using the original dataset.
