### ISSUE TITLE
key error when using monoscene to visualize pkl

### ISSUE THREAD

**Issue by lizhiwen19900709** [hustvl/Symphonies#2]
File "monoscene/scripts/visualization/kitti_vis_pred.py", line 169, in main
    T_velo_2_cam = b["T_velo_2_cam"]
KeyError: 'T_velo_2_cam'

![image](https://github.com/hustvl/Symphonies/assets/15767823/0d3ce2d0-f22a-4bf7-bb46-111c5221169e)

**Comment by npurson** [comment]
Thank you for your interest in our project. I apologize for the inconvenience caused by this issue.

In brief, you can fix the key error on lines 169-172 of the original MonoScene visualization script by modifying it as follows:

```python
T_velo_2_cam = b['cam_pose']  # instead of b['T_velo_2_cam']
vox_origin = np.array([0, -25.6, -2])

y_pred = b['pred']  # instead of b['y_pred']
```

I'd like to mention that we haven't released the complete visualization scripts yet, as we are currently working on unifying the interface for visualizing various datasets. This is still an ongoing process, and we will update the visualization file as soon as it is completed.

Please let me know if you have any other questions! Once again, thank you for your interest in our project and for bringing this issue to our attention. Your feedback is valuable in helping us improve the project.
