### ISSUE TITLE
Can you provide the depth file used during training?

### ISSUE THREAD

**Issue by StudyingFuFu** [hustvl/Symphonies#21]
Can you provide the depth file used during training? I can't run the indicators in the paper.
The highest miou that came out was 14.6, which is quite different from 15.03 in the paper.

**Comment by npurson** [comment]
Hello, thanks for your interest in our work and for reaching out.

To begin, could you please clarify whether your mentioned mIoU score of  14.6 was evaluated on the **val** set locally, or was obtained by submitting to the official evaluation server for the **test** set.

* If it's from the val set, our reported mIoU on val is 14.89. Slight differences like these can be expected due to the high variability observed on the SemanticKITTI dataset, particularly if you only run the experiments once or twice.
* If, however, your result is derived from the test set, we would appreciate if you could share both your val mIoU and relevant logs.

Regarding the generated depth files, I think such performance should not be caused that. You can verify this by loading our provided checkpoints to view the results.

Besides, here are some troubleshooting steps you can try if the above suggestions do not resolve the issue:

1. Compare you training logs against ours to spot any anomalies.
2. Repeat the experiment for several times to see if this is a fluctuation.

Please let us know if you have any other questions!

**Comment by StudyingFuFu** [comment]
thank you, 14.6 is from the val set
Which version of lightning are you using?
I have to change ddp in the configuration file to ddp_find_unused_parameters_true to avoid program errors.

**Comment by npurson** [comment]
I think we were using Lightning 1.8, and the default behavior of "ddp" has been changed to "ddp_find_unused_parameters=False" in Lightning 2.0. You can refer to "Speeding up DDP with find_unused_parameters (#16611)" section available at https://lightning.ai/releases/2.0.0/ for more details.

I agree with your solution and you don't have to downgrade the version of Lightning, as long as the training time doesn't become apparently slower (typically < 1 day for SemanticKIITI).

**Comment by StudyingFuFu** [comment]
OK, thank you for your answer.
