### ISSUE TITLE
How to prepare SemanticKitti dataset?

### ISSUE THREAD

**Issue by FiveLu** [hustvl/Symphonies#3]
```
data_root: /horizon-bucket/aidi_public_data/SemanticKitti/origin
label_root: /horizon-bucket/aidi_public_data/SemanticKitti/origin/processed/labels
depth_root: /home/users/haoyi.jiang/data/kitti_depth
```
Hi. I am so confused about the structure  of SemanticKitti dataset, especially `data_root` and `label_path`.  It's not elaborated in README. Could you tell me what it contains? And how to get it ?  

Thank you very much!

**Comment by npurson** [comment]
Thank you for bringing this issue to our attention. I apologize for any confusion caused by the lack of detailed instructions for dataset preparation in our README.

For a quick fix, I would suggest referring to the documentation in [VoxFormer](https://github.com/NVlabs/VoxFormer/blob/main/docs/prepare_dataset.md) (where the preprocessed labels are provided, while the voxelized psuedo point cloud and query proposals are not necessary for our method) or [MonoScene](https://github.com/astra-vision/MonoScene#semantickitti) (you may need run the preprocessing yourself) for now. After that, don't forget to generate the depth prediction as referred to in our [README](https://github.com/hustvl/Symphonies#prepare-dataset).

As an additional note, I would like to mention that during our data preparation, we followed the instructions provided by MonoScene and have not specifically tested the VoxFormer dataset, but it seems they should be consistent.

We will work on improving the clarity and comprehensiveness of our README accordingly. Please let us know if you have any other questions.

**Comment by FiveLu** [comment]
> 
I think I get it. I have run VoxFormer recently, so i could use `labels` and `sequences` directly (modify the path in yaml). The extra thing I need to do is generate the folder `depth`.
Thanks!
